name = "VintageOptControl"
uuid = "baaf2c55-359b-4809-9af1-56c4b57e479e"
authors = ["Michael Freiberger"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
